# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LoginUserModel(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LoginUserModel - a model defined in OpenAPI

        grant_type: The grant_type of this LoginUserModel [Optional].
        username: The username of this LoginUserModel.
        password: The password of this LoginUserModel.
        token: The token of this LoginUserModel [Optional].
    """

    grant_type: Optional[str] = None
    username: str
    password: str
    token: Optional[str] = None

LoginUserModel.update_forward_refs()
