# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class RolesUsersModel(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RolesUsersModel - a model defined in OpenAPI

        user_id: The user_id of this RolesUsersModel.
        role_id: The role_id of this RolesUsersModel.
    """

    user_id: int
    role_id: int

RolesUsersModel.update_forward_refs()
