# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class RoleModelAll(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RoleModelAll - a model defined in OpenAPI

        id: The id of this RoleModelAll [Optional].
        name: The name of this RoleModelAll [Optional].
        description: The description of this RoleModelAll [Optional].
    """

    id: Optional[int] = None
    name: Optional[str] = None
    description: Optional[str] = None

RoleModelAll.update_forward_refs()
