# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class UserModel(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserModel - a model defined in OpenAPI

        email: The email of this UserModel.
        username: The username of this UserModel.
        first_name: The first_name of this UserModel.
        middle_name: The middle_name of this UserModel [Optional].
        last_name: The last_name of this UserModel.
        password: The password of this UserModel.
        disabled: The disabled of this UserModel [Optional].
    """

    email: EmailStr
    username: str
    first_name: str
    middle_name: Optional[str] = None
    last_name: str
    password: str
    disabled: Optional[bool] = None

UserModel.update_forward_refs()
