# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from models.role_model import RoleModel


class UserModelAll(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserModelAll - a model defined in OpenAPI

        id: The id of this UserModelAll [Optional].
        uid: The uid of this UserModelAll [Optional].
        email: The email of this UserModelAll [Optional].
        username: The username of this UserModelAll [Optional].
        first_name: The first_name of this UserModelAll [Optional].
        middle_name: The middle_name of this UserModelAll [Optional].
        last_name: The last_name of this UserModelAll [Optional].
        password: The password of this UserModelAll [Optional].
        date_registerd: The date_registerd of this UserModelAll [Optional].
        disabled: The disabled of this UserModelAll [Optional].
        roles: The roles of this UserModelAll [Optional].
    """

    id: Optional[int] = None
    uid: Optional[str] = None
    email: Optional[EmailStr] = None
    username: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    last_name: Optional[str] = None
    password: Optional[str] = None
    date_registerd: Optional[datetime] = None
    disabled: Optional[bool] = None
    roles: Optional[List[RoleModel]] = None

UserModelAll.update_forward_refs()
